spring.application.name=susu

# DEPLOYMENT ENV
target.deployment.stage=uat
app.environment = uat

# SQLITE
spring.datasource.url=jdbc:h2:mem:SusuLocalDb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# SWAGGER UI CONFIG
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/susu/${target.deployment.stage}/swagger.html
springdoc.swagger-ui.tagsSorter=alpha
